//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string addUserButton {
            get {
                return ResourceManager.GetString("addUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string AdmonMenu {
            get {
                return ResourceManager.GetString("AdmonMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential security.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential Security System.
        /// </summary>
        public static string ApplicationName_Title {
            get {
                return ResourceManager.GetString("ApplicationName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application parameter.
        /// </summary>
        public static string ApplicationParameters {
            get {
                return ResourceManager.GetString("ApplicationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create applicacion parameter.
        /// </summary>
        public static string ApplicationParameters_Create_Tile {
            get {
                return ResourceManager.GetString("ApplicationParameters_Create_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit application parameter.
        /// </summary>
        public static string ApplicationParameters_Edit_Title {
            get {
                return ResourceManager.GetString("ApplicationParameters_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application parameters.
        /// </summary>
        public static string ApplicationParametersMenu {
            get {
                return ResourceManager.GetString("ApplicationParametersMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BacktoList {
            get {
                return ResourceManager.GetString("BacktoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs.
        /// </summary>
        public static string CatalogsMenu {
            get {
                return ResourceManager.GetString("CatalogsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonials.
        /// </summary>
        public static string ColonialMenu {
            get {
                return ResourceManager.GetString("ColonialMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Date.
        /// </summary>
        public static string DateStart {
            get {
                return ResourceManager.GetString("DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Are you sure you want to delete the {0}?.
        /// </summary>
        public static string Delete_AskToDelete {
            get {
                return ResourceManager.GetString("Delete_AskToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} could not be deleted..
        /// </summary>
        public static string Delete_ErrorMessage {
            get {
                return ResourceManager.GetString("Delete_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} has been deleted correctly..
        /// </summary>
        public static string Delete_OkMessage {
            get {
                return ResourceManager.GetString("Delete_OkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough information to carry out the request..
        /// </summary>
        public static string ErrorMessage_InsufficientInformation {
            get {
                return ResourceManager.GetString("ErrorMessage_InsufficientInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Event.
        /// </summary>
        public static string Event_Create_Title {
            get {
                return ResourceManager.GetString("Event_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Event.
        /// </summary>
        public static string Event_Edit_Title {
            get {
                return ResourceManager.GetString("Event_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string EventMenu {
            get {
                return ResourceManager.GetString("EventMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Event Type.
        /// </summary>
        public static string EventType_Create_Tile {
            get {
                return ResourceManager.GetString("EventType_Create_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Event Type.
        /// </summary>
        public static string EventType_Edit_Title {
            get {
                return ResourceManager.GetString("EventType_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Types.
        /// </summary>
        public static string EventTypeMenu {
            get {
                return ResourceManager.GetString("EventTypeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External User.
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External User Type.
        /// </summary>
        public static string ExternalType {
            get {
                return ResourceManager.GetString("ExternalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create External User.
        /// </summary>
        public static string ExternalType_Create_Tile {
            get {
                return ResourceManager.GetString("ExternalType_Create_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit External User.
        /// </summary>
        public static string ExternalType_Edit_Title {
            get {
                return ResourceManager.GetString("ExternalType_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create External User.
        /// </summary>
        public static string ExternalUser_Create_Tile {
            get {
                return ResourceManager.GetString("ExternalUser_Create_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit External User.
        /// </summary>
        public static string ExternalUser_Edit_Title {
            get {
                return ResourceManager.GetString("ExternalUser_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Users.
        /// </summary>
        public static string ExternalUserMenu {
            get {
                return ResourceManager.GetString("ExternalUserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string HelloText {
            get {
                return ResourceManager.GetString("HelloText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int Number.
        /// </summary>
        public static string InNumber {
            get {
                return ResourceManager.GetString("InNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} could not be added..
        /// </summary>
        public static string Insert_ErrorMessage {
            get {
                return ResourceManager.GetString("Insert_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} has been added correctly..
        /// </summary>
        public static string Insert_OkMessage {
            get {
                return ResourceManager.GetString("Insert_OkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plate.
        /// </summary>
        public static string LicensePlate {
            get {
                return ResourceManager.GetString("LicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Location.
        /// </summary>
        public static string Location_Create_Tile {
            get {
                return ResourceManager.GetString("Location_Create_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Location.
        /// </summary>
        public static string Location_Edit_Title {
            get {
                return ResourceManager.GetString("Location_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string LocationMenu {
            get {
                return ResourceManager.GetString("LocationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Type.
        /// </summary>
        public static string LocationType {
            get {
                return ResourceManager.GetString("LocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Location Type.
        /// </summary>
        public static string LocationType_Create_Tile {
            get {
                return ResourceManager.GetString("LocationType_Create_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Location Type.
        /// </summary>
        public static string LocationType_Edit_Title {
            get {
                return ResourceManager.GetString("LocationType_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Types.
        /// </summary>
        public static string LocationTypeMenu {
            get {
                return ResourceManager.GetString("LocationTypeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Location-User.
        /// </summary>
        public static string LocationUser_Edit_Title {
            get {
                return ResourceManager.GetString("LocationUser_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string LocationUser_lName {
            get {
                return ResourceManager.GetString("LocationUser_lName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string LocationUser_UName {
            get {
                return ResourceManager.GetString("LocationUser_UName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location-User.
        /// </summary>
        public static string LocationUserMenu {
            get {
                return ResourceManager.GetString("LocationUserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Surname.
        /// </summary>
        public static string MotherSurname {
            get {
                return ResourceManager.GetString("MotherSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Assignation.
        /// </summary>
        public static string NoAssignation {
            get {
                return ResourceManager.GetString("NoAssignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        public static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Number.
        /// </summary>
        public static string OutNumber {
            get {
                return ResourceManager.GetString("OutNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Action.
        /// </summary>
        public static string Permission_Action {
            get {
                return ResourceManager.GetString("Permission_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Area.
        /// </summary>
        public static string Permission_Area {
            get {
                return ResourceManager.GetString("Permission_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Code.
        /// </summary>
        public static string Permission_Code {
            get {
                return ResourceManager.GetString("Permission_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Controller.
        /// </summary>
        public static string Permission_Controller {
            get {
                return ResourceManager.GetString("Permission_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Permission.
        /// </summary>
        public static string Permission_Create_Title {
            get {
                return ResourceManager.GetString("Permission_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Description.
        /// </summary>
        public static string Permission_Desc {
            get {
                return ResourceManager.GetString("Permission_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Permission.
        /// </summary>
        public static string Permission_Edit_Title {
            get {
                return ResourceManager.GetString("Permission_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Permission_Id {
            get {
                return ResourceManager.GetString("Permission_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Name.
        /// </summary>
        public static string Permission_Name {
            get {
                return ResourceManager.GetString("Permission_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string PermissionMenu {
            get {
                return ResourceManager.GetString("PermissionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred during the {0} process.
        /// </summary>
        public static string Process_ErrorMessage {
            get {
                return ResourceManager.GetString("Process_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process {0} has been executed correctly..
        /// </summary>
        public static string Process_OkMessage {
            get {
                return ResourceManager.GetString("Process_OkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RolesMenu {
            get {
                return ResourceManager.GetString("RolesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tag.
        /// </summary>
        public static string Tag_Create_Tile {
            get {
                return ResourceManager.GetString("Tag_Create_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tag.
        /// </summary>
        public static string Tag_Edit_Title {
            get {
                return ResourceManager.GetString("Tag_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Code.
        /// </summary>
        public static string TagCode {
            get {
                return ResourceManager.GetString("TagCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagMenu {
            get {
                return ResourceManager.GetString("TagMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersMenu {
            get {
                return ResourceManager.GetString("UsersMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Brand.
        /// </summary>
        public static string VehicleBrand {
            get {
                return ResourceManager.GetString("VehicleBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model.
        /// </summary>
        public static string VehicleModel {
            get {
                return ResourceManager.GetString("VehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Year.
        /// </summary>
        public static string VehicleYear {
            get {
                return ResourceManager.GetString("VehicleYear", resourceCulture);
            }
        }
    }
}
