// <auto-generated />
namespace Persistence.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExternalBinnacle_11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExternalBinnacle_11));
        
        string IMigrationMetadata.Id
        {
            get { return "201909190445400_ExternalBinnacle_11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
