// <auto-generated />
namespace Persistence.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class versionInicialBD1_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(versionInicialBD1_0));
        
        string IMigrationMetadata.Id
        {
            get { return "201902212044580_versionInicialBD1_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
