// <auto-generated />
namespace Persistence.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class permissionUserUpdateForeignKeysRemoveAuditory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(permissionUserUpdateForeignKeysRemoveAuditory));
        
        string IMigrationMetadata.Id
        {
            get { return "201904121829376_permissionUserUpdateForeignKeysRemoveAuditory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
