//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinnacleTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BinnacleTypes()
        {
            this.ExternalBinnacles = new HashSet<ExternalBinnacles>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Binnacle_Id { get; set; }
        public string Description { get; set; }
    
        public virtual Binnacles Binnacles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalBinnacles> ExternalBinnacles { get; set; }
    }
}
