//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinnaclePhotoes
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string DeletedBy { get; set; }
        public string Image { get; set; }
        public Nullable<int> Binnacle_Id { get; set; }
        public Nullable<int> BinnaclePhotoType_Id { get; set; }
        public Nullable<int> ExternalBinnacle_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual BinnaclePhotoTypes BinnaclePhotoTypes { get; set; }
        public virtual Binnacles Binnacles { get; set; }
        public virtual ExternalBinnacles ExternalBinnacles { get; set; }
    }
}
