//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecureGateEntities : DbContext
    {
        public SecureGateEntities()
            : base("name=SecureGateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ApplicationParameters> ApplicationParameters { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Audiences> Audiences { get; set; }
        public virtual DbSet<BinnaclePhotoes> BinnaclePhotoes { get; set; }
        public virtual DbSet<BinnaclePhotoTypes> BinnaclePhotoTypes { get; set; }
        public virtual DbSet<Binnacles> Binnacles { get; set; }
        public virtual DbSet<BinnacleTypes> BinnacleTypes { get; set; }
        public virtual DbSet<Bulletins> Bulletins { get; set; }
        public virtual DbSet<EventLocations> EventLocations { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<EventTypes> EventTypes { get; set; }
        public virtual DbSet<ExternalBinnaclePhotoes> ExternalBinnaclePhotoes { get; set; }
        public virtual DbSet<ExternalBinnacles> ExternalBinnacles { get; set; }
        public virtual DbSet<ExternalPhotoes> ExternalPhotoes { get; set; }
        public virtual DbSet<Externals> Externals { get; set; }
        public virtual DbSet<ExternalTypes> ExternalTypes { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<LocationTelephones> LocationTelephones { get; set; }
        public virtual DbSet<LocationTypes> LocationTypes { get; set; }
        public virtual DbSet<LocationUserNotifications> LocationUserNotifications { get; set; }
        public virtual DbSet<LocationUsers> LocationUsers { get; set; }
        public virtual DbSet<LocationVehicles> LocationVehicles { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<PermissionRoles> PermissionRoles { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<PermissionUsers> PermissionUsers { get; set; }
        public virtual DbSet<PhotoTypes> PhotoTypes { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<UserBinnacles> UserBinnacles { get; set; }
    }
}
