//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalBinnacles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalBinnacles()
        {
            this.BinnaclePhotoes = new HashSet<BinnaclePhotoes>();
            this.ExternalBinnaclePhotoes = new HashSet<ExternalBinnaclePhotoes>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string DeletedBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public string ExternalName { get; set; }
        public string ColonialName { get; set; }
        public string LicensePlateText { get; set; }
        public string LocationText { get; set; }
        public string ExternalTypeText { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
        public Nullable<int> BinnacleType_Id { get; set; }
        public Nullable<int> External_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinnaclePhotoes> BinnaclePhotoes { get; set; }
        public virtual BinnacleTypes BinnacleTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalBinnaclePhotoes> ExternalBinnaclePhotoes { get; set; }
        public virtual Externals Externals { get; set; }
    }
}
