//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionRoles
    {
        public int Id { get; set; }
        public string ApplicationRole_Id { get; set; }
        public Nullable<int> Permission_Id { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual Permissions Permissions { get; set; }
    }
}
